# FILE PATH: clusters/homelab/infrastructure-controllers.yaml
# PURPOSE: Reconcile controllers required by platform configuration and
#          application workloads. Node metrics is reconciled separately.
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-controllers
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 30m
  path: ./kubernetes/infrastructure/controllers/core
  prune: true
  wait: true

  sourceRef:
    kind: GitRepository
    name: flux-system
