# FILE PATH:
# kubernetes/applications/homelab/mccruden-site/service.yaml
# PURPOSE: Expose the site internally to Traefik.
---
apiVersion: v1
kind: Service
metadata:
  name: mccruden-site
  namespace: mccruden-site
  labels:
    app.kubernetes.io/name: mccruden-site
    app.kubernetes.io/part-of: mccruden-com
spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: mccruden-site

  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
      appProtocol: http
