#ENC[AES256_GCM,data:/D57S0qblKdIoKU=,iv:kgfyr9Vx/XLotGE1SPJMQeQqm6yY2IQPelXVeueXuDY=,tag:M3XEdPGGNhYUAoW6iWiZvQ==,type:comment]
#ENC[AES256_GCM,data:Z5+lYcdeOXyhGhGP6Tp/Xrtct4J0rEAuwfXke5oRIV6Ub+YOEyrpPHS2fFgonMrZg8uPyCvpl/YDlFAzl8pT4iuFDtUxTcsUGvuo9Po6Yg==,iv:g2K0rHkoexCxzUIP01p+4zdSHhMMjXMPrSE0ssh/cGk=,tag:6/O6VeDgY9udpT9LC3TssQ==,type:comment]
#ENC[AES256_GCM,data:JvBBxasHD0oY,iv:jZu3/rfgXcE7FOhfHrymNL17ywr8LpFX6TbqdM8ZrI8=,tag:kokDEtpZMdfqPOD648kLTA==,type:comment]
#ENC[AES256_GCM,data:d6if/4QDbzLhlCWYWkcfAhR0jdrFD51FaNIxoJconZ6cL0mqL7dnUNfjlITgZKV72VZ0J6zzAONkGcLQ6QuPJncdM7qc8k8=,iv:rieVtvrdV27romlf4+HLkICAllmcM8rDumGEzGoS1WA=,tag:jyHR2oBwqHK2P/LUZlDC+g==,type:comment]
#ENC[AES256_GCM,data:nM3W4B7a9SDIwoY17Lpca4OKipe7nST8hkyVv2Mdq6X5dBpncZNrsnrO8cVSmv0uUVClrVsn,iv:WP/IajOI7Ob/fmdcwISIkhvHc0RvIMrfpLJj5BO+QbQ=,tag:6G4lTxpcNmJr9kFfiqvPzw==,type:comment]
apiVersion: ENC[AES256_GCM,data:qvs=,iv:ZUrJqd5aZvRma+yyGXSYU2XwQuIqoAaYCSCsZl5kfaI=,tag:w0pX2NffSoqTXti2VMYrkg==,type:str]
kind: ENC[AES256_GCM,data:f/84zAP8,iv:rWrcE3DVZYfdJqUHZifV70d1gdX4hKg6CJ3lfzXlDMo=,tag:T8NAtI9QxS9jilOX+R5+6A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RYvtvPB/BT7wt+yZrfMcz5aBRiDOvHkY,iv:fPNtgm1ONRLvTcv2UHLasCUcUYUFRRuq5KBVhQqWZ5k=,tag:GVqAILbA+Lj3G6XqRLnwmg==,type:str]
    namespace: ENC[AES256_GCM,data:fExB9ky7ZD5Ww2LYh8efow==,iv:P3S/dwTv+Ceua5PlpEvZ7mNyKXFXkfkFtkfgWL72+HQ=,tag:GQrZb+3rDxDDYLUNQ4ITpQ==,type:str]
type: ENC[AES256_GCM,data:wU1sruXe,iv:un79ZOrX2a3jLoHP100Z2Aof0Fy6tlaAg/gMGXMdXfk=,tag:0fOZ49SZCsbH+sPhqbxGNg==,type:str]
stringData:
    tenantId: ENC[AES256_GCM,data:6PsqQrr+O5tSjgspoo5PXR2Q0Arz8PI9S6yYq2lw90A7MDO2,iv:z8RJwMUGGHBKwvZttRAgcw5ezoXkXlRpm7Ulx6vKI8k=,tag:HS2CVQHLRsRNF83X26llSg==,type:str]
    clientId: ENC[AES256_GCM,data:2ElmYnL2OIKV+PDH/9dyfGm4IBhHrUjQDUkBS/NnUY/e0SwE,iv:l2Mg2DxjYhwkoV2+5XkFMsQC2nIgZVJVT+4tdj2orvk=,tag:lfPQvCjrlU16nlK5S3FT6w==,type:str]
    clientSecret: ENC[AES256_GCM,data:KVXM7eTsBVtuR54d0B5284z6pv3G0/+Fbe+1n7t/ASGtfLs1ShLsOg==,iv:od+xCEDYrSxITjq6ProQAU3jD3PvFMX4/nTRSRrfZ/s=,tag:uZJaP+E78DEU29+X6D1MzA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSVI2ZHAxR2JOOFJPell1
            VUUyL045Mi9FaVBhanQyZnpuT1FIQTBpTUJjClNrRXRLU0RTTS9SRW9PRVJ3bTRs
            bUIzd1J2OHBoYzRrWVJkMnByYzNxUkEKLS0tIFgvTDczNTlHOENDMno4cjY4Q0Rz
            Y2FZU0xUOXdoTmF6Qkk5c0V5Q1puVmMKw9por45RlaC6oOZuL+o5Ja48EZY9RU+A
            rf5cH3t1+8YGMTMhs3D8HIfSF6tMS1hDCzwECP9TJsAmGRPyBRuPCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nsf8chjscmz3lsq22w66862g0adwf40yxp62yu4uf6e6vwh7jacqy6nzuf
    lastmodified: "2026-07-13T15:45:48Z"
    mac: ENC[AES256_GCM,data:pILj+/8Qum79ffILxzc6QdWEBsmWDr9ABLqVIb14ub0yndp5onSslnM2DyjoXmNJCmm2fGYS5GyHkcklBFqM/RkEVUuSp67M0/XBw8Gx63Nf5LHjfGKTV5jlcgxeK3a7ENTi9mT2gWmU3K699e83HozDi37JVA6ykOiGtzE1qLo=,iv:B85P6WQwYu5HRVLi9El5m3GmsLKgllGK3+A6vUrEbJ4=,tag:nFVfe8ms+0EYH7BkA3VckA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
