# FILE PATH:
# kubernetes/infrastructure/configs/external-secrets/clustersecretstore.yaml
# PURPOSE: Provide cluster-wide access to Azure Key Vault through ESO.
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-key-vault
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      environmentType: PublicCloud
      tenantId: "9176d973-762b-40a4-9464-5a836c9c5b04"
      vaultUrl: "https://kvhomelab91c977.vault.azure.net/"

      authSecretRef:
        clientId:
          name: azure-keyvault-bootstrap
          namespace: external-secrets
          key: clientId

        clientSecret:
          name: azure-keyvault-bootstrap
          namespace: external-secrets
          key: clientSecret
