# FILE PATH:
# kubernetes/infrastructure/configs/external-secrets/kustomization.yaml
# PURPOSE: Configure Azure Key Vault access for External Secrets Operator.
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - azure-credentials.sops.yaml
  - clustersecretstore.yaml
  - cloudflare-api-token.yaml
