# FILE PATH: roles/prereqs/defaults/main.yml
---
kubernetes_prerequisite_packages:
  - conntrack-tools
  - containernetworking-plugins
  - curl
  - ethtool
  - iproute
  - iproute-tc
  - iptables
  - socat
  - runc
  - cri-tools
kubernetes_kernel_modules:
  - overlay
  - br_netfilter
kubernetes_sysctl_values:
  net.bridge.bridge-nf-call-iptables: 1
  net.bridge.bridge-nf-call-ip6tables: 1
  net.ipv4.ip_forward: 1
