# FILE PATH: roles/prereqs/defaults/main.yml
---
kubernetes_prereq_packages:
  - conntrack-tools
  - containernetworking-plugins
  - curl
  - ethtool
  - iproute
  - iproute-tc
  - iptables
  - socat
kubernetes_kernel_modules: [overlay, br_netfilter]
