# FILE PATH:
# kubernetes/infrastructure/configs/cert-manager/clusterissuer-production.yaml
# PURPOSE: Configure Let's Encrypt production with Cloudflare DNS-01.
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: stephen@mccruden.com
    server: https://acme-v02.api.letsencrypt.org/directory

    privateKeySecretRef:
      name: letsencrypt-production-account-key

    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
