# FILE PATH: roles/kubernetes_node/meta/main.yml
---
galaxy_info:
  role_name: kubernetes_node
  author: Stephen McCruden
  description: Homelab Kubernetes node kubernetes node role.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Fedora
      versions: [all]
dependencies: []
