# FILE PATH: roles/verification/meta/main.yml
---
galaxy_info:
  role_name: verification
  author: Stephen McCruden
  description: Homelab Kubernetes node verification role.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Fedora
      versions: [all]
dependencies: []
