# FILE PATH: roles/container_runtime/meta/main.yml
---
galaxy_info:
  role_name: container_runtime
  author: Stephen McCruden
  description: Homelab Kubernetes node container runtime role.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Fedora
      versions: [all]
dependencies: []
