# FILE PATH: roles/firewall/defaults/main.yml
---
kubernetes_firewall_zone: kubernetes
control_plane_ports:
  - 6443/tcp
  - 2379-2380/tcp
  - 10250/tcp
  - 10257/tcp
  - 10259/tcp
worker_ports:
  - 10250/tcp
  - 10256/tcp
nodeport_range: 30000-32767/tcp
