# FILE PATH: roles/hardening/meta/main.yml
---
galaxy_info:
  role_name: hardening
  author: Stephen McCruden
  description: Homelab Kubernetes node hardening role.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Fedora
      versions: [all]
dependencies: []
