# FILE PATH: roles/prereqs/meta/main.yml
---
galaxy_info:
  role_name: prereqs
  author: Stephen McCruden
  description: Homelab Kubernetes node prereqs role.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Fedora
      versions: [all]
dependencies: []
