# FILE PATH: kubernetes/applications/homelab/kustomization.yaml
# PURPOSE: Entry point for homelab application workloads.
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []
