# FILE PATH: roles/package_manager/meta/main.yml
---
galaxy_info:
  role_name: package_manager
  author: Stephen McCruden
  description: Homelab Kubernetes node package manager role.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Fedora
      versions: [all]
dependencies: []
